FROM registry.gitlab.inria.fr/charms/meshtools:master AS meshtools

#FROM debian:buster-slim
FROM debian:stable-slim

COPY ./set-compass-ids.sh /etc/local/sbin/set-compass-ids.sh
RUN chown root:root /etc/local/sbin/set-compass-ids.sh && \
    chmod 755 /etc/local/sbin/set-compass-ids.sh

COPY ./add-compass-user.sh /etc/local/sbin/add-compass-user.sh
RUN chown root:root /etc/local/sbin/add-compass-user.sh && \
    chmod 700 /etc/local/sbin/add-compass-user.sh && \
    /etc/local/sbin/add-compass-user.sh
RUN mkdir -p /localfs
VOLUME /localfs

COPY ./customize-bashrc.sh /etc/customize-bashrc.sh
RUN echo "\n# ComPASS specific" >> /etc/bash.bashrc && \
    cat /etc/local/sbin/set-compass-ids.sh >> /etc/bash.bashrc && \
    cat /etc/customize-bashrc.sh >> /etc/bash.bashrc && \
    rm /etc/customize-bashrc.sh

# We install python3.7-dev because python3-scipy python3-matplotlib 
# that are installed in work environment depend on python-3.7
# Is this an inconsistency in debian buster?
RUN apt-get update && apt-get install --yes --no-install-recommends \
    python3-dev \
    python3-numpy \
    python3-setuptools \
    python3-pip \
 && apt-get clean 

# Meshtools installation
WORKDIR /wheels
COPY --from=meshtools /wheels/MeshTools-0.0.1-cp35-cp35m-linux_x86_64.whl .
RUN pip3 install MeshTools-0.0.1-cp35-cp35m-linux_x86_64.whl

WORKDIR /localfs
RUN rm -rf /wheels
