# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

image: docker:stable

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
  # and https://gitlab.inria.fr/charms/ComPASS/issues/72
  DOCKER_DRIVER: overlay2
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  # cf. https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"
  # Project specifc variables
  CI_REGISTRY_IMAGE: registry.gitlab.inria.fr/charms/compass

services:
  - docker:stable-dind

stages:
  - build_docker_environments
  - build
  - test
  - release

before_script:
  - echo "Preparing build..."
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.inria.fr
   
after_script:
  - echo "You might do some cleanup here"

# here we build specific docker environments
# (cf. miscellaneous/docker/README.md)
build_docker_environments:
  stage: build_docker_environments
  tags:
    - build
  only:
    - /^docker_evt_.*$/
  script:
    - cd miscellaneous/docker
    # We cannot retrieve the latest wheel from MeshTools master branch
    # using gitlab API beacause the use of CI_JOB_TOKEN is a premium feature
    # (charms/MeshTools project id is 8447 on gitlab.inria.fr)
    # # We rely on curl to retrieve MeshTools and we are in an alpine based image (hence apk)
    # - apk add --no-cache curl
    # The command is wrapped into single quotes since it contains a colon
    # - 'curl --location --output wheel.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.inria.fr/api/v4/projects/8447/jobs/artifacts/master/download?job=build"''
    - docker pull registry.gitlab.inria.fr/charms/meshtools/master-wheel:latest
    - docker run -v $PWD:/localfs --user $UID:`id -g $USER` registry.gitlab.inria.fr/charms/meshtools/master-wheel:latest
    - /bin/sh -e generate_environments.bash wheel/*.whl
    - rm -rf wheel


build:
  stage: build
  tags:
    - build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --force-rm --cache-from $CI_REGISTRY_IMAGE:latest --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
#TODO
#how to use docker cache ? split dockerfile to have a build image.fixed.
#how to prevent from rebuild all code when only test change.
# add gitlab runner docker in slave 2 to run dind
# clean mechanism for docker images ?

sanity_check:
  stage: test
  tags:
    - test
  script:
    - echo "Job running with id"
    - id
    - echo "unit test with" $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker run --rm -v $PWD/test/sanity:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG heat_source_analytical_1D.py
    - docker run --rm -v $PWD/test/sanity:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG heat_source_analytical.py
    - docker run --rm -v $PWD/test/sanity:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG vertical_column_temperature.py
    - docker run --rm -v $PWD/test/sanity:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG vertical_fracture.py

pytest_run:
  stage: test
  tags:
    - test
  script:
    - docker run --rm -v $PWD/test/fast:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --pytest

petrel_test:
  stage: test
  tags:
    - test
  script:
    - docker run --rm -v $PWD/test/cases/petrel:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG doublet_on_cartesian_grid_petrel.py
  
parallel_test:
  stage: test
  tags:
    - test
  script:
    - docker run --rm -v $PWD/test/sanity:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --parallel vertical_column_temperature.py
    - docker run --rm -v $PWD/test/fast:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --parallel test_nodeflags_on_tetmesh.py

time_bulk_scripts:
  stage: test
  tags:
    - test
  script:
    - docker run -v $PWD/test/bulk:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --bash ./time_all_scripts.bash

reactive_transport_test:
  stage: test
  tags:
    - test
  script:
    - docker run -v $PWD/test/experimental/reactive_transport:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG simple_ionexchange.py

master_release:
  stage: release
  tags:
    - release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
   # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - master
  when: on_success

tag_release:
  stage: release
  tags:
    - release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  when: on_success

