variables:
  COMPASS_SDK: 0.1.0
  # We assume that is fine to run mpi as root in a docker container
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

image:
  name: "registry.gitlab.inria.fr/charms/compass-images/sdk:${COMPASS_SDK}"

stages:
  - check
  - build
  - test
  - release
  - documentation

check format:
  stage: check
  tags:
    - build
    - docker
  script:
    # We could check format only for merge requests
    # using only merge_requests
    # and CI_MERGE_REQUEST_SOURCE_BRANCH_SHA and CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    # variables but the latest are not correclyt set
    - git fetch origin ${CI_DEFAULT_BRANCH}
    - merge_base=$(git merge-base origin/${CI_DEFAULT_BRANCH} HEAD)
    - changed_files=$(git diff --no-ext-diff --name-only ${merge_base}...HEAD)
    - echo "Changed files:" ${changed_files}
    - pre-commit run --files ${changed_files}

build:
  stage: build
  tags:
    - docker
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
    - dist/
    expose_as: wheel
    when: on_success

baseline tests:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/baseline
    - >
      for f in \
        MO2/MO2-1d-casea.py \
        MO2/MO2-1d-caseb.py \
        MO2/MO2-1d-casec.py \
        MO3/MO3-casea.py \
        MO3/MO3-caseb.py \
        MO4/MO4.py \
        SO1/SO1.py \
        SO2/SO2.py
      do
        python3 $f
      done

baseline parallel tests:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/baseline
    - >
      for f in \
        MO2/MO2-1d-casea.py \
        MO2/MO2-1d-caseb.py \
        MO2/MO2-1d-casec.py \
        MO3/MO3-casea.py \
        MO3/MO3-caseb.py \
        MO4/MO4.py \
        SO1/SO1.py \
        SO2/SO2.py
      do
        mpirun -n `nproc` python3 $f
      done

pytest:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/fast # change directory otherwise import ComPASS conflicts with source
    - python3 -m pytest

time bulk scripts:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test
    - python3 utilities/pool.py bulk

linalg:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/linalg
    - python3 options_test.py

more sanity tests:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test
    - >
      for f in \
        sanity/heat_source_analytical_1D.py \
        sanity/heat_source_analytical.py \
        sanity/vertical_column_temperature.py \
        sanity/vertical_fracture.py \
        unit/check_settings.py \
        unit/init_states.py \
        unit/vertical_well.py \
        unit/postprocess_producers.py \
        unit/check_petrophysics.py \
        unit/dof_families.py \
        unit/well_connectivity.py \
        unit/test_simulation_global_functions.py \
        unit/check_balances_two_phases.py \
        unit/random_wellheads.py \
        unit/test_set_array.py \
        unit/test_close_perforations.py \
        unit/display_model_elements.py \
        unit/one_wedge_cell_with_well.py \
        unit/check_well_information.py \
        unit/display_model_elements.py \
        unit/test_diphasic_equilibrium.py \
        unit/phase_pressure_absent_phase.py \
        unit/two_cells_fracture_zero.py \
        unit/salome/test_standalone.py \
        unit/salome/test_with_compass.py
      do
        ( cd ${f%/*}; python3 ${f##*/} )
      done

postprocess:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/unit
    - python3 two_cells.py
    - python3 -m ComPASS.postprocess -s -C output-two_cells

petrel:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test/cases/petrel
    - python3 doublet_on_cartesian_grid_petrel.py

various parallel test:
  stage: test
  tags:
    - docker
    - test
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - cd test
    - >
      for f in \
        sanity/vertical_column_temperature.py \
        fast/test_nodeflags_on_tetmesh.py \
        unit/distribute_fracture_edge_info.py \
        unit/select_fracture_edges_with_node_info.py \
        unit/check_balances.py \
        unit/check_settings.py \
        unit/vertical_wells.py \
        unit/check_petrophysics.py \
        unit/dof_families.py \
        bulk/chain_random_wells.py \
        unit/well_connectivity.py \
        unit/test_close_perforations.py
      do
        mpirun -n `nproc` python3 $f
      done

container release:
  stage: release
  tags:
    - build
    - docker
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    TARGET_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cp -rv dist docker/
    - docker build --force-rm -t $TARGET_IMAGE --build-arg SDK_TAG="${COMPASS_SDK}" docker
    - docker push $TARGET_IMAGE
    - docker tag $TARGET_IMAGE ${TARGET_IMAGE%\:*}:latest
    - docker push ${TARGET_IMAGE%\:*}:latest
  after_script:
    - docker logout $CI_REGISTRY
    - docker rm -f $TARGET_IMAGE
    - docker rm -f ${TARGET_IMAGE%\:*}:latest

pages:
  stage: documentation
  tags:
    - docker
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  before_script:
    - python3 -m pip install --no-index -f dist ComPASS
  script:
    - rootdir=$(pwd)
    - cd ${rootdir}/docs/doxygen
    - doxygen Doxyfile
    - cd ${rootdir}/docs
    - cp -vf ../README.rst ../INSTALL.rst ../LICENSE.rst .
    - sphinx-apidoc ../ComPASS -o python_reference
    - sphinx-build . html
    - cd ${rootdir}
    - mkdir -p public/core_reference
    - cp -rf docs/html/* public
    - cp -rf docs/doxygen/html/* public/core_reference
  artifacts:
    paths:
    - public
