# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: docker:latest

image: docker:stable

stages:
    #- build
    #- test
    #- deploy
    
variables:
  CONTAINER_IMAGE: registry.gitlab.inria.fr/charms/compass
  #DOCKER_DRIVER: overlay2

#services:
#  - docker:dind

# first build epos_gui image to run in docker.
before_script:
  - echo "Preparing build..."
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.inria.fr
   

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build:
  stage: build
  script:
    - echo "building.."
    - docker build --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
 #   - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
  #  - docker push $CONTAINER_IMAGE:latest


deploy:
  stage: deploy
  script:
    - echo "deploy"
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    #  - docker build -t epos-gui:latest --build-arg SHORT_GIT_SHA=$SHORT_SHA .
    #  - docker stop epos-gui || true && docker rm epos-gui || true
    #  - docker run --rm -p 8080:80 --name epos-gui -td epos-gui
    
unit test:
  stage: test
  script:
    - echo "unit test"
  #  - docker run --rm -td epos-gui-dev node_modules/.bin/ng test -sr --browsers PhantomJS

