repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/fortran-lang/fprettify
    rev: v0.3.5
    hooks:
    -   id: fprettify
-   repo: https://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    -   id: clang-format
        exclude: 'third-parties/.*'
        args: [-style=file]
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
      additional_dependencies: [pyyaml]
      args: ['-i']
#    - id: cmake-lint
