[build-system]
requires = ["scikit-build", "numpy", "wheel", "setuptools>=61", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "ComPASS/_version.py"
